stages:
  - security
  - lint
  - tests
  - build
  - deploy
  - cve
  - publish

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - scheduler_failure
      - stuck_or_timeout_failure
      - api_failure
      - job_execution_timeout
      - data_integrity_failure

variables:
  REGISTRY_URL: "registry.home.chupin.xyz"
  GITLEAKS_VERSION: "latest"
  HELM_VERSION: "latest"
  TRIVY_VERSION: "latest"
  CHART_RELEASER_VERSION: "latest"

  TRIVY_SEVERITY: MEDIUM,HIGH,CRITICAL
  IGNORE_TRIVY_CVE: true
  SKIP_DEPLOY: false

  CR_GIT_REPO: homebox-helm
  CR_SKIP_EXISTING: true

  HELM_NAMESPACE: e2e
  HELM_RELEASE: homebox
  HELM_TIMEOUT: 10m
  HELM_STORAGE_CLASS: local-path

include:
  - local: .gitlab/build.yml
    rules:
      - if: "$CI_COMMIT_TAG == null"
  - local: .gitlab/release.yml
    rules:
      - if: $CI_COMMIT_TAG
